### ISSUE TITLE
Add Races to the game.

### ISSUE THREAD

**Issue by LluisFelip** [LluisFelip/RandomAdventureRoguelike2PoolOfIdeas#3]
**A short explanation of your idea**
Add Races to the New Game character creation screen.

**Describe your idea**
I'd love to be able to select a Race for my character, and depending on the Race selected, it could have different stats and/or skills/traits.

**Additional context**
The classical Human, Dwarf, Elf, Orc, etc… would be nice!

**Comment by AdcakeArts** [comment]
Frost wildling
this is more of a sub variant of elf. most features would be the same as an elf. but proficiency in clubs and axes instead of bows and daggers. they have cold immunity, they are rare to see out side of high mountainous regions.


heres is a rough sketch for their appearance.
![1576772687255](https://user-images.githubusercontent.com/59060820/71190735-f9581100-2239-11ea-9e60-9217c7473d08.png)

**Comment by AdcakeArts** [comment]
i really don't know if this race fits more as a random enemy or not in all honesty.

**Comment by LluisFelip** [comment]
Maybe as an enemy yes :)

Let me add a spoiler here of what races are coming to the game (as soon as I finish the development of the feature :D):

- HUMAN
- DWARF
- HALFLING
- GNOME
- ELF
- DROW
- UNDEAD
- ORC
- LIZARD
- UNKNOWN

I'll give more details soon :)

**Comment by Rotpa** [comment]
Beastmen. Half human, half beast.

**Comment by Palendalaar28** [comment]
I have some Examples: -dragonborne
- gobelin
- barbarian
- fairy
-half-orc
- half-elf
-elemental
-ogre
-behemoth
- machine
I hope help something :D
